<header class="p-3 bg-warning">
    <h1 class="text-center">WELCOME</h1>    
        <nav class="navbar navbar-expand-lg bg-faded justify-content-center">
            <div class="navbar-nav">
                <a class="nav-link" href="/">Home</a>
                <a class="nav-link" href="/contact">Contact</a>
                <a class="nav-link" href="/?param=1&name=Rogério&id=500">Home with Params</a>
            </div>
        </nav>    
</header>